### ISSUE TITLE
Monthly SRR

### ISSUE THREAD

**Issue by zsiders** [lidach/CampLabScallop#10]
We proposed this, we might not want it after yesterday's discussion

- [ ] Add monthly stock-recruit relationship to merge all spawning variants together

_Originally posted by @zsiders in https://github.com/lidach/CampLabScallop/issues/5#issuecomment-733772570_

**Comment by EdCamp** [comment]
You're talking about calculating recruits monthly, as opposed to the accumulator function?

**Comment by zsiders** [comment]
@EdCamp, yes.
