### ISSUE TITLE
accumulated spawning biomass into SR relationship

### ISSUE THREAD

**Issue by lidach** [lidach/CampLabScallop#2]
Account for continuous nature of fishery:

- [x] monthly accumulator to track spawning biomass over a year

**Comment by nickcfisch** [comment]
Not sure how continuous nature of the fishery applies here but I understood the main goal here to be, given it is a monthly model, we need an accumulator group that accounts for individuals that have spawned across the year. This is opposed to taking the spawning biomass in month 12 to predict recruits in month 13. So a certain proportion of indv will have spawned in month 11, 10 and so on. 

This task may get superseded by another, where we consider making a monthly SR relationship (still unsure how DD mort would apply there) but I will code this task and we can discuss at the next meeting. 

What I've done here is just made a new vector called prop_spawn which describes the proportion of indv that spawn in each month (dimensions of length 12).

**Comment by nickcfisch** [comment]
Adjustments look good, just one question; why does prop_spawn need to be normalized?

**Comment by zsiders** [comment]
You don't need to, it does help to prevent multiple spawners. The semelparity/iteroparity is certainly something we need to run down better. If bay scallops are like most northern species at the southern limit of their range in FL then it probably depends a lot on environmental/physiological conditions.
